name = "mapit"
type = "javascript"
account_id = "8cb468d0dae016094c99457e601ff46b"
workers_dev = false

[build]
command = "pnpm build"
cwd = "./"
watch_paths = ["client/src/**/*.tsx", "client/src/**/*.ts", "client/src/**/*.css"]

[[build.upload]]
format = "service-worker"
